DROP TABLE IF EXISTS CITY;

CREATE SEQUENCE "CITY_SEQ"
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 1
    NOCACHE
    NOCYCLE;

CREATE TABLE CITY (
    id BIGINT NOT NULL DEFAULT nextval('CITY_SEQ') PRIMARY KEY,
    postcode VARCHAR(6) NOT NULL,
    name VARCHAR(50) NOT NULL,
    departement VARCHAR(2) NOT NULL
);